---
# tasks file for proxmox-vm
# tags: status
- name: get current status
  proxmox_kvm:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_password }}"
    validate_certs: "{{ proxmox_validate_certs }}"
    node: "{{ node }}"
    name: "{{ vm_name|default(omit) }}"
    vmid: "{{ vm_vmid|default(omit) }}"
    state: current
  register: results
- name: print current status
  debug:
    msg: "{{ vm_name|default('') }} ({{ vm_vmid|default('') }}): {{ results.status }}"
